
package com.example.services.helloworld;

import javax.xml.ws.WebFault;
import com.example.types.helloworld.FatalErrorList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "FatalErrorList", targetNamespace = "http://example.com/types/helloworld")
public class FatalError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FatalErrorList faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FatalError(String message, FatalErrorList faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FatalError(String message, FatalErrorList faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.types.helloworld.FatalErrorList
     */
    public FatalErrorList getFaultInfo() {
        return faultInfo;
    }

}
