
package com.example.services.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Hello World service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorld_Service", targetNamespace = "http://example.com/services/helloworld", wsdlLocation = "file:/home/ppalaga/orgs/fuse/issues/ENTESB-9506-cxf-subject-is-null/src/example-camel-cxf-jaxws/src/main/resources/HelloWorld.wsdl")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.example.services.helloworld.HelloWorldService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.example.services.helloworld.HelloWorldService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/ppalaga/orgs/fuse/issues/ENTESB-9506-cxf-subject-is-null/src/example-camel-cxf-jaxws/src/main/resources/HelloWorld.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/ppalaga/orgs/fuse/issues/ENTESB-9506-cxf-subject-is-null/src/example-camel-cxf-jaxws/src/main/resources/HelloWorld.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://example.com/services/helloworld", "HelloWorld_Service"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorld_Port")
    public HelloWorldPortType getHelloWorldPort() {
        return super.getPort(new QName("http://example.com/services/helloworld", "HelloWorld_Port"), HelloWorldPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorld_Port")
    public HelloWorldPortType getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/services/helloworld", "HelloWorld_Port"), HelloWorldPortType.class, features);
    }

}
