
package com.example.services.helloworld;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.security.auth.Subject;

import org.apache.cxf.message.Message;
import org.apache.cxf.phase.PhaseInterceptorChain;
import org.apache.cxf.security.LoginSecurityContext;
import org.apache.cxf.security.SecurityContext;

import com.example.types.helloworld.FatalErrorList;
import com.example.types.helloworld.Greeting;
import com.example.types.helloworld.Person;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 *
 */

public class HelloWorldImpl implements HelloWorldPortType {

    Logger logger = Logger.getLogger(HelloWorldImpl.class.getName());

    /*
     * (non-Javadoc)
     *
     * @see com.example.services.helloworld.HelloWorldPortType#sayHello(com.example.types.helloworld.Person)
     */
    @Override
    public Greeting sayHello(final Person person) throws FatalError {

        if (person.getFirstName() == null || person.getFirstName().trim().length() == 0) {

            final FatalErrorList faultInfo = new FatalErrorList();
            faultInfo.setMessage("First name is null");
            faultInfo.setCode("F0001");
            faultInfo.setCausationData("person.getFirstName():" + person.getFirstName());

            final FatalError fatalError = new FatalError("Protocol Error", faultInfo);
            throw fatalError;
        }

        Message message = PhaseInterceptorChain.getCurrentMessage();
        Subject subject = ((LoginSecurityContext) message.get(SecurityContext.class)).getSubject();
        if (subject == null) {
            logger.log(Level.SEVERE, "Policy context not available ");
            throw new SecurityException("Could not locate policy context");
        } else {
            logger.info("Subject:" + subject + " Principal::" + subject.getPrincipals());
        }

        final Greeting greeting = new Greeting();
        greeting.setGreeting("Hello " + person.getFirstName() + " " + person.getLastName() + " !");
        return greeting;
    }

}
