
package com.example.services.helloworld;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.security.auth.Subject;
import javax.security.jacc.PolicyContext;
import javax.security.jacc.PolicyContextException;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.cxf.interceptor.InInterceptors;
import org.jboss.security.SecurityConstants;
import org.jboss.ws.api.annotation.EndpointConfig;

import com.example.types.helloworld.FatalErrorList;
import com.example.types.helloworld.Greeting;
import com.example.types.helloworld.ObjectFactory;
import com.example.types.helloworld.Person;

import javax.jws.WebService;
import javax.security.auth.Subject;
import javax.security.jacc.PolicyContext;
import javax.security.jacc.PolicyContextException;

import org.jboss.security.SecurityConstants;
import org.apache.cxf.interceptor.InInterceptors;
import org.jboss.ws.api.annotation.EndpointConfig;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 *
 */

@WebService(
        serviceName = "HelloWorld_Service",
        portName = "HelloWorld_Port",
        targetNamespace = "http://example.com/services/helloworld",
        endpointInterface = "com.example.services.helloworld.HelloWorldPortType",
        wsdlLocation = "WEB-INF/classes/HelloWorld.wsdl"
)
@EndpointConfig(configFile = "WEB-INF/jaxws-endpoint-config.xml", configName = "UsernameTokenEndpointImplConfig")
@InInterceptors(interceptors = {
      "org.jboss.wsf.stack.cxf.security.authentication.SubjectCreatingPolicyInterceptor",
      "com.example.services.interceptor.POJOEndpointAuthorizationInterceptor"}
)
public class HelloWorldImpl implements HelloWorldPortType {

    Logger logger = Logger.getLogger(HelloWorldImpl.class.getName());

    /*
     * (non-Javadoc)
     *
     * @see com.example.services.helloworld.HelloWorldPortType#sayHello(com.example.types.helloworld.Person)
     */
    @Override
    public Greeting sayHello(final Person person) throws FatalError {

        if (person.getFirstName() == null || person.getFirstName().trim().length() == 0) {

            final FatalErrorList faultInfo = new FatalErrorList();
            faultInfo.setMessage("First name is null");
            faultInfo.setCode("F0001");
            faultInfo.setCausationData("person.getFirstName():" + person.getFirstName());

            final FatalError fatalError = new FatalError("Protocol Error", faultInfo);
            throw fatalError;
        }

        Subject subject = null;
        try {
            subject = (Subject) PolicyContext.getContext(SecurityConstants.SUBJECT_CONTEXT_KEY);

            if (subject == null) {
                logger.log(Level.SEVERE, "Policy context not available ");
                throw new SecurityException("Could not locate policy context");
            } else {
                logger.info("Subject:" + subject + " Principal::" + subject.getPrincipals());
            }

        } catch (final PolicyContextException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        final Greeting greeting = new Greeting();
        greeting.setGreeting("Hello " + person.getFirstName() + " " + person.getLastName() + " !");
        return greeting;
    }

}
